name: Release
on:
  push:
    tags:
      - 'v*'
  # release:
  #   types:
  #     - released
  #     - prereleased
  # push:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  release-artifacts:
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.conf.target }}

      - name: Build executable
        run: cargo build --release --target ${{ matrix.conf.target }}

      - name: Zip (Windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          7z a artifact-mover-${{ matrix.conf.target }}.zip ./target/${{ matrix.conf.target }}/release/artifact-mover.exe

      - name: Zip (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: zip -j artifact-mover-${{ matrix.conf.target }}.zip target/${{ matrix.conf.target }}/release/artifact-mover

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifact-mover-${{ matrix.conf.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
